#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x

IMAGE_NAME="mediagoblin-image"
CONTAINER_NAME="mediagoblin-container"
PORT=8080

docker version

docker build \
  --tag "$IMAGE_NAME" \
  .

# Clear any previous container.
docker rm -f "$CONTAINER_NAME" &> /dev/null || true

docker run \
  --tty \
  --detach \
  --publish "${PORT}:6543" \
  --name "$CONTAINER_NAME" \
  "$IMAGE_NAME"

# Wait at most 15 seconds until server is listening on a TCP port.
timeout 15 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' localhost "${PORT}"

curl \
  --retry 15 \
  --retry-delay 2 \
  --fail \
  "http://localhost:${PORT}/" > /dev/null
