#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x

IMAGE_NAME="mediagoblin-image"
CONTAINER_NAME="mediagoblin-container"
PORT=8080

docker version

docker build \
  --tag "$IMAGE_NAME" \
  .

# Clear any previous container.
docker rm -f "$CONTAINER_NAME" &> /dev/null || true

docker run \
  --tty \
  --detach \
  --publish "${PORT}:6543" \
  --name "$CONTAINER_NAME" \
  "$IMAGE_NAME"

# Give the container a little time to start up.
sleep 15

curl \
  --retry 15 \
  --retry-delay 2 \
  --fail \
  "http://localhost:${PORT}/" > /dev/null
